## Sun et al. data

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd

k_shot = 10
n_outer_splits = 10
n_inner_splits = 10
balanced_or_unbalanced = "unbalanced"

abundance_data = pd.read_csv(
    "../../data/sun_et_al_data/mpa4_species_profile_preprocessed.csv",
    index_col=0,
    header=0,
)
metadata = pd.read_csv(
    "../../data/sun_et_al_data/sample_group_species_preprocessed2.csv",
    index_col=0,
    header=0,
)  # 2 is for metadata with all columns

In [ ]:
from loguru import logger
import numpy as np
import json
import os
import sys

sys.path.append("../..")

import src.data.dataloader as dataloader
from src.global_vars import BASE_DATA_DIR


study_names: list = metadata["Project_1"].unique().tolist()
assert len(study_names) == 36


def get_train_and_test_df_from_data(
    abundance_data: pd.DataFrame, metadata: pd.DataFrame, test_study: str
):
    test_metadata_df = metadata[metadata["Project_1"] == test_study]
    test_data_df = abundance_data.loc[test_metadata_df.index]
    train_metadata_df = metadata.drop(index=test_metadata_df.index)
    train_data_df = abundance_data.drop(index=test_data_df.index)

    return train_data_df, train_metadata_df, test_data_df, test_metadata_df


data_splits_for_all_studies = {}
for test_study in study_names:
    print(test_study)
    (
        cross_val_data_selection,
        train_data_df,
        train_metadata_df,
        test_data_df,
        test_metadata_df,
    ) = dataloader.get_cross_validation_sun_et_al_data_splits(
        abundance_data,
        metadata,
        test_study=test_study,
        k_shot=k_shot,
        balanced_or_unbalanced=balanced_or_unbalanced,
        n_outer_splits=n_outer_splits,
        n_inner_splits=n_inner_splits,
    )

    print(cross_val_data_selection)
    display(test_data_df)
    raise SystemExit()

# create folder if non-existent
save_in = BASE_DATA_DIR / "sun_et_al_data" / "pre_selected_data_splits"
os.makedirs(save_in, exist_ok=True)

with open(save_in / f"AAA{k_shot}shot_{balanced_or_unbalanced}.json", "w") as f:
    json.dump(data_splits_for_all_studies, f, indent=4)

logger.info(
    f"Saved data splits for all studies in {save_in / f'{k_shot}_{balanced_or_unbalanced}.json'}"
)
logger.info(f"Finished creating data splits for all studies")

# some checks

HanL_2021

,s__Phocaeicola_plebeius,s__Faecalibacterium_prausnitzii,s__Ruminococcus_sp_NSJ_71,s__Eubacterium_rectale,s__Bacteroides_uniformis,s__Clostridium_sp_AF15_49,s__Lachnospira_eligens,s__Roseburia_sp_AF02_12,s__Phocaeicola_vulgatus,s__Ruminococcus_bicirculans,...,s__Rodentibacter_myodis,s__Rhodococcus_hoagii,s__Pseudomonas_psychrophila,s__Pseudomonas_sp_DG56_2,s__Providencia_rustigianii,s__Pseudomonas_vranovensis,s__Pseudomonas_taetrolens,s__Pseudomonas_deceptionensis,s__Desulfobulbus_oralis,s__Bacteroides_reticulotermitis
Sample,,,,,,,,,,,,,,,,,,,,,
K0060,-0.002058,0.184277,-0.002058,0.010536,0.309898,-0.002058,-0.002058,-0.002058,0.403450,-0.002058,...,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058,-0.002058
C0049,-0.002719,0.166884,-0.002719,0.056527,0.098562,0.103452,0.029597,0.107380,0.159132,-0.002719,...,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719,-0.002719
K0137,-0.001418,-0.001418,-0.001418,-0.001418,0.457555,-0.001418,-0.001418,-0.001418,0.264819,-0.001418,...,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418,-0.001418
HK0040,-0.002499,0.251978,-0.002499,0.042219,0.173000,-0.002499,0.191819,-0.002499,0.559047,0.078698,...,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499,-0.002499
HK0093,-0.002274,0.231146,-0.002274,0.110352,0.457501,-0.002274,-0.002274,-0.002274,0.500729,0.087311,...,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274,-0.002274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HC0003,-0.002458,0.233796,-0.002458,0.098652,0.232410,-0.002458,0.061821,-0.002458,-0.002458,0.105500,...,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458,-0.002458
C0004,0.009778,0.060625,-0.002604,0.049163,0.355501,0.024446,0.047822,-0.002604,0.231573,0.100435,...,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604,-0.002604
C0100,-0.002804,0.125194,-0.002804,0.022246,0.205168,0.049478,-0.002804,-0.002804,0.139634,0.262092,...,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804,-0.002804
A0006,0.043278,0.211523,-0.002513,-0.002513,0.639295,-0.002513,0.074129,0.023200,0.235061,-0.002513,...,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513,-0.002513
C0037,-0.002909,0.186029,-0.002909,0.186210,0.573612,0.058808,0.014759,-0.002909,0.074346,0.090528,...,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909,-0.002909

SystemExit:

c:\Users\shaya\Documents\TU_projects\master_thesis\.thesis_venv\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
md = metadata[metadata["Project_1"] == "HanL_2021"]
test_support = [
    "HK0066",
    "HK0031",
    "HK0054",
    "HK0041",
    "HC0005",
    "HK0014",
    "HK0018",
    "HK0065",
    "HK0004",
    "HK0053",
    "K0182",
    "C0080",
    "C0043",
    "K0064",
    "K0190",
    "K0154",
    "A0032",
    "K0044",
    "K0095",
    "K0031",
]

print(len(cross_val_data_selection[0][0]))

print(cross_val_data_selection[0][1][0][1])
val_study1_name = cross_val_data_selection[0][1][0][0]
val_study1_data = cross_val_data_selection[0][1][0][1]

md = metadata[metadata["Project_1"] == val_study1_name]
print(val_study1_name)
display(md)
display(md.loc[cross_val_data_selection[0][1][0][1]])

20
['SAMEA2737855', 'SAMEA2737814', 'SAMEA2737823', 'SAMEA2737831', 'SAMEA2737705', 'SAMEA2737826', 'SAMEA2737874', 'SAMEA2737734', 'SAMEA2737825', 'SAMEA2737858', 'SAMEA2737724', 'SAMEA2737746', 'SAMEA2737760', 'SAMEA2737697', 'SAMEA2737672', 'SAMEA2737718', 'SAMEA2737751', 'SAMEA2737774', 'SAMEA2737678', 'SAMEA2737859']
ZhangX_2015

,Group,Group_1,Group_2,LevelB,LevelA,group,Project,Project_1,Project_2,LevelA2,LevelA3,LevelA4,LevelA5,Age,Gender,BMI,Location_1,Location,sequence_type,DNA_extract_type
Sample,,,,,,,,,,,,,,,,,,,,
SAMEA2737843,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,NaN,NaN,NaN,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737705,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,57.0,Female,26.2,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737694,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,36.0,Female,26.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737775,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,55.0,Female,24.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737873,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,23.0,Female,19.5,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SAMEA2737683,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,25.0,Female,19.5,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737740,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,53.0,Female,25.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737725,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,48.0,Male,NaN,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737802,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,46.0,Female,22.9,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737674,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,61.0,Female,21.3,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012

,Group,Group_1,Group_2,LevelB,LevelA,group,Project,Project_1,Project_2,LevelA2,LevelA3,LevelA4,LevelA5,Age,Gender,BMI,Location_1,Location,sequence_type,DNA_extract_type
Sample,,,,,,,,,,,,,,,,,,,,
SAMEA2737855,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,37.0,Male,28.4,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737814,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,54.0,Male,NaN,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737823,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,46.0,Female,21.4,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737831,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,41.0,Female,21.3,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737705,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,57.0,Female,26.2,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737826,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,45.0,Female,28.4,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737874,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,57.0,Female,22.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737734,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,34.0,Male,22.6,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737825,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,52.0,Male,20.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737858,Control,Control,Control,RA,immune disease,Control,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,19.0,Female,19.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737724,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,36.0,Female,23.9,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737746,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,41.0,Male,17.4,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737760,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,55.0,Female,25.4,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737697,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,66.0,Male,22.8,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737672,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,64.0,Female,22.0,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737718,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,49.0,Female,18.8,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737751,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,64.0,Male,21.8,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737774,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,67.0,Female,20.8,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737678,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,55.0,Male,25.8,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012
SAMEA2737859,Disease,Disease,Disease,RA,immune disease,Onset,ZhangX_2015.RA,ZhangX_2015,Discover,immune disease,immune disease,RA,immune disease,45.0,Female,22.9,Beijing,Beijing,Illumina HiSeq 2000,QinJ_2012

In [13]:
%load_ext autoreload
%autoreload 2

import sys

sys.path.append("../../")
import pandas as pd
import os

import src.data.sun_et_al as sea
from src.data.dataloader import (
    get_cross_validation_sun_et_al_data_splits,
)
from torch.utils.data import DataLoader
from src.helper_function import column_rename_for_sun_et_al_metadata

# data = pd.read_csv(
#     "../../data/sun_et_al_data/mpa4_species_profile_preprocessed.csv",
#     index_col=0,
#     header=0,
# )
# metadata = pd.read_csv(
#     "../../data/sun_et_al_data/sample_group_species_preprocessed.csv",
#     index_col=0,
#     header=0,
# )  # 2 is for metadata with all columns

(
    test_loop_data_selection,
    val_loop_data_selection,
    train_data,
    train_metadata,
    test_data,
    test_metadata,
) = get_cross_validation_sun_et_al_data_splits(
    data,
    metadata,
    test_study="HeQ_2017",
    k_shot=10,
    balanced_or_unbalanced="balanced",
    n_outer_splits=10,
    n_inner_splits=3,
)

# train_metadata = column_rename_for_sun_et_al_metadata(train_metadata)
# test_metadata = column_rename_for_sun_et_al_metadata(test_metadata)


n_cpus = int(os.environ.get("SLURM_CPUS_PER_TASK", 1))
# Create Datasets for DataLoader
print(train_data.shape, train_metadata.shape)
train = sea.MicrobiomeDataset(train_data, train_metadata)
# eval = sea.MicrobiomeDataset(
#     test_data, test_metadata, preselected_support_set=list(test_loop_data_selection.values())[0]
# )

# Create DataLoaders
sampler = sea.BinaryFewShotBatchSampler(
    train,
    10,
    include_query=True,
    shuffle=True,
)
train_loader = DataLoader(
    train, batch_sampler=sampler, num_workers=n_cpus, pin_memory=True
)

# sampler = sea.BinaryFewShotBatchSampler(
#     eval,
#     10,
#     include_query=True,
#     shuffle=False,
#     shuffle_once=False,
#     training=False,
# )
# eval_loader = DataLoader(
#     eval, batch_sampler=sampler, num_workers=n_cpus, pin_memory=True
# )

for i, (X, y) in enumerate(train_loader):
    print(X.shape, y.shape)
    print(X[0].shape, y[0].shape)
    print(X[1].shape, y[1].shape)
    print(X[2].shape, y[2].shape)

# test dataloaders
# loader = list(train_loader)
# print(len(loader))
# # print(loader[0])

# loader = list(eval_loader)
# print(len(loader))
# # print(loader[0])

# print(train.group_to_label_idx_per_class)
# print(train.labels)
# print(train.group_to_label_idx_per_class[33])

# print(train.labels[train.group_to_label_idx_per_class[33][0][:10]])
# print(train.samples[train.group_to_label_idx_per_class[33][0][:10]])
# display(train_data.iloc[train.group_to_label_idx_per_class[33][0][:10]])
# print(train_metadata.loc[train_data.iloc[train.group_to_label_idx_per_class[33][0][:10]].index])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

2025-04-21 12:12:40.949 | INFO     | src.data.dataloader:get_cross_validation_sun_et_al_data_splits:358 - Loading data splits from C:\Users\shaya\Documents\TU_projects\master_thesis\data\sun_et_al_data\selected_data_splits\HeQ_2017\10shot_nOuter10_nInner3_HeQ_2017_69189786.yml

(6205, 2557) (6205, 20)

KeyError: 'project'

In [ ]:
import pandas as pd

stunt_data = pd.read_csv("../../data/sun_et_al_data/stunt/stunt_mpa4_species_profile_preprocessed.csv", index_col=0, header=0, nrows=10000)

:

In [ ]:
stunt_data.isna().sum().sum()

np.int64(0)