In [9]:
import pandas as pd
import numpy as np


def print_full_df(x):
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)
    pd.set_option("display.width", None)
    pd.set_option("display.max_colwidth", None)
    display(x)
    pd.reset_option("display.max_rows")
    pd.reset_option("display.max_columns")
    pd.reset_option("display.width")
    pd.reset_option("display.float_format")
    pd.reset_option("display.max_colwidth")

data = pd.read_table("../../data/lam_et_al_data/abundance_data.tsv", header=0, index_col=0)
metadata = pd.read_csv("../../data/lam_et_al_data/metadata.csv", header=0, index_col=0, usecols=[1,2,3,4])

data = data.rename(columns=lambda x: x.split(".")[0])
data = data.T

In [10]:
display(data.head())
display(metadata.head())

#OTU ID,28116,817,820,2763022,2650158,2785531,2528203,2755405,2650157,2715212,...,2745895,77152,1280052,364102,28214,2420305,1371,326454,408956,38304
SAMEA104142072,1363363,1308506,1213209,90319,58129,145774,108741,91436,24491,21038,...,0,0,0,0,0,0,0,0,0,0
SAMEA104142073,49988,46281,164611,14662,12476,36095,35975,22774,150975,10882,...,0,0,0,0,0,0,0,0,0,0
SAMEA104142074,1168514,246884,224378,148418,81018,54737,43740,38119,239062,24779,...,0,0,0,0,0,0,0,0,0,0
SAMEA104142075,66674,214698,405676,40622,22152,115613,78033,53837,50901,25423,...,0,0,0,0,0,0,0,0,0,0
SAMEA104142076,76275,66293,124481,15042,9490,26640,30269,24662,64565,16527,...,0,0,0,0,0,0,0,0,0,0

                              Study_Accession Run_Accession   Phenotype
Sample Accession or Sample ID
SAMEA104142072                     PRJEB21528    ERR2017580  Overweight
SAMEA104142073                     PRJEB21528    ERR2017579  Overweight
SAMEA104142074                     PRJEB21528    ERR2017578  Overweight
SAMEA104142075                     PRJEB21528    ERR2017568  Overweight
SAMEA104142076                     PRJEB21528    ERR2017564     Healthy

In [ ]:
grouped = metadata.groupby("Study_Accession")
studywise_nonzero_features = {}

for group, idx in grouped.groups.items():
    print(f"Group: {group}")
    data_of_group = data.loc[idx, :]
    metadata_of_group = metadata.loc[idx, :]
    # print columns of all zeros
    zero_columns = data_of_group.columns[(data_of_group == 0).all()]
    print(zero_columns[:5])
    display(metadata_of_group.value_counts("Phenotype"))
    studywise_nonzero_features[group] = set(list(data_of_group.columns))

Group: PRJEB10878
Index([1108, 226665, 78535, 2587858, 475375], dtype='int64', name='#OTU ID')

Phenotype
CRC    70
Name: count, dtype: int64

Group: PRJEB11532
Index([1096856, 1232493, 1751046, 1248330, 311808], dtype='int64', name='#OTU ID')

Phenotype
Healthy    881
Name: count, dtype: int64

Group: PRJEB12123
Index([78535, 1232493, 2490939, 35793, 1761895], dtype='int64', name='#OTU ID')

Phenotype
Obesity    104
Healthy    101
Name: count, dtype: int64

Group: PRJEB1220
Index([2665175, 1096856, 78535, 2576356, 2742671], dtype='int64', name='#OTU ID')

Phenotype
Ulcerative colitis    66
Obesity               55
Healthy               48
Overweight            17
Crohns disease        11
Name: count, dtype: int64

Group: PRJEB12449
Index([2665175, 2594454, 2692235, 1096856, 1108], dtype='int64', name='#OTU ID')

Phenotype
CRC           49
Healthy       30
Overweight    12
Obesity        8
Name: count, dtype: int64

Group: PRJEB12947
Index([2665175, 1096856, 1920116, 35789, 35792], dtype='int64', name='#OTU ID')

Phenotype
Obesity    13
Name: count, dtype: int64

Group: PRJEB13870
Index([658666, 155322, 2665175, 2529386, 412384], dtype='int64', name='#OTU ID')

Phenotype
Healthy    35
Name: count, dtype: int64

Group: PRJEB15371
Index([78535, 2490939, 35793, 1751046, 1761895], dtype='int64', name='#OTU ID')

Phenotype
Crohns disease    47
Healthy           39
Overweight         7
Obesity            1
Name: count, dtype: int64

Group: PRJEB1690
Index([2665175, 2594454, 37931, 1096856, 1612552], dtype='int64', name='#OTU ID')

Phenotype
Healthy    16
Name: count, dtype: int64

Group: PRJEB1786
Index([1096856, 29429, 78535, 563169, 2742632], dtype='int64', name='#OTU ID')

Phenotype
T2D           46
Healthy       17
Overweight    17
Obesity        6
Name: count, dtype: int64

Group: PRJEB19090
Index([313598, 1896175, 669041, 1644130, 2719911], dtype='int64', name='#OTU ID')

Phenotype
Healthy    10
Name: count, dtype: int64

Group: PRJEB21528
Index([1449781, 233181, 319426, 2781976, 405041], dtype='int64', name='#OTU ID')

Phenotype
ACVD          152
Healthy        75
Overweight     40
Obesity         8
Name: count, dtype: int64

Group: PRJEB4336
Index([1096856, 78535, 563169, 2725997, 2742671], dtype='int64', name='#OTU ID')

Phenotype
Obesity       69
Healthy       39
Overweight     4
Name: count, dtype: int64

Group: PRJEB6070
Index([1096856, 2576356, 2742630, 2742648, 1232493], dtype='int64', name='#OTU ID')

Phenotype
CRC                 92
Healthy             41
advanced adenoma    40
Overweight          12
Obesity              6
Name: count, dtype: int64

Group: PRJEB6337
Index([2665175, 1096856, 29429, 78535, 2576356], dtype='int64', name='#OTU ID')

Phenotype
Healthy       87
Overweight     6
Name: count, dtype: int64

Group: PRJEB6456
Index([1096856, 78535, 563169, 1394, 2742630], dtype='int64', name='#OTU ID')

Phenotype
Healthy    89
Name: count, dtype: int64

Group: PRJEB6997
Index([78535, 1232493, 2490939, 1761895, 311808], dtype='int64', name='#OTU ID')

Phenotype
Rheumatoid Arthritis    92
Healthy                 55
Overweight              27
Obesity                  4
Name: count, dtype: int64

Group: PRJEB7774
Index([2742648, 1232493, 2742674, 77038, 1751046], dtype='int64', name='#OTU ID')

Phenotype
CRC                 43
advanced adenoma    42
Healthy             21
Obesity             20
Overweight          20
Name: count, dtype: int64

Group: PRJEB8094
Index([1896175, 1476901, 1458492, 1756149, 249402], dtype='int64', name='#OTU ID')

Phenotype
Healthy       16
Overweight     4
Name: count, dtype: int64

Group: PRJNA177201
Index([658666, 155322, 2683680, 2665175, 2529386], dtype='int64', name='#OTU ID')

Phenotype
Healthy       8
Overweight    3
Name: count, dtype: int64

Group: PRJNA268964
Index([2594454, 1096856, 1920116, 78535, 2725997], dtype='int64', name='#OTU ID')

Phenotype
Healthy       20
Overweight     8
Obesity        3
Name: count, dtype: int64

Group: PRJNA278393
Index([155322, 2665175, 1096856, 202462, 1108], dtype='int64', name='#OTU ID')

Phenotype
Healthy    18
Name: count, dtype: int64

Group: PRJNA290729
Index([298656, 247481, 2053832, 155322, 2529386], dtype='int64', name='#OTU ID')

Phenotype
Obesity    14
Name: count, dtype: int64

Group: PRJNA299502
Index([155322, 2665175, 2594454, 1108, 29459], dtype='int64', name='#OTU ID')

Phenotype
T2D           19
Obesity       11
Overweight     4
Healthy        1
Name: count, dtype: int64

Group: PRJNA305507
Index([412384, 2594454, 2692235, 1096856, 1108], dtype='int64', name='#OTU ID')

Phenotype
Healthy    31
Name: count, dtype: int64

Group: PRJNA319574
Index([1096856, 78535, 2742671, 2742648, 1232493], dtype='int64', name='#OTU ID')

Phenotype
Healthy    467
Name: count, dtype: int64

Group: PRJNA328899
Index([658666, 155322, 2420310, 78535, 2742632], dtype='int64', name='#OTU ID')

Phenotype
Healthy    107
Name: count, dtype: int64

Group: PRJNA373879
Index([658666, 155322, 260554, 2665175, 412384], dtype='int64', name='#OTU ID')

Phenotype
Healthy       16
Overweight     3
Name: count, dtype: int64

Group: PRJNA385949
Index([155322, 2665175, 412384, 2594454, 1727214], dtype='int64', name='#OTU ID')

Phenotype
Crohns disease        6
Ulcerative colitis    5
Healthy               3
Name: count, dtype: int64

Group: PRJNA389280
Index([155322, 260554, 2665175, 412384, 691437], dtype='int64', name='#OTU ID')

Phenotype
Crohns disease        43
Ulcerative colitis    25
Healthy               17
Name: count, dtype: int64

Group: PRJNA422434
Index([1108, 78535, 1232493, 2364271, 2587858], dtype='int64', name='#OTU ID')

Phenotype
T2D           171
Healthy        61
Overweight     48
Obesity         2
Name: count, dtype: int64

Group: PRJNA48479
Index([1096856, 78535, 563169, 2742630, 1232493], dtype='int64', name='#OTU ID')

Phenotype
Healthy    219
Name: count, dtype: int64